site_name: "Portfolio: Ing. en 🤖🧠 y 📈📊"
theme:
  name: material
  language: es
  icon:
    logo: material/memory
  favicon: assets/favicon.svg
  features:
    - navigation.sections
    - navigation.indexes
  custom_dir: overrides
extra_css:
  - assets/stylesheets/extra.css
extra_javascript:
  - assets/javascripts/extra.js
plugins:
  - search
  - awesome-pages
  - git-revision-date-localized:
      fallback_to_build_date: true
  - glightbox
  - macros
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.emoji
  - pymdownx.tasklist:
      custom_checkbox: true
